### ISSUE TITLE
Parent Directory plugin fails on spaces in directory name

### ISSUE THREAD

**Issue by ghost** [mank319/Kupfer-Plugins#1]
Opening the parent directory fails if there are spaces in any of the parent directory names. I think the file path is not getting escaped correctly?

**Comment by Manuel-Kehl** [comment]
Oh wow, how could I have not recognized that yet? I'll investigate into it when I find some time 😉

**Comment by Manuel-Kehl** [comment]
I just recognized your pull request. Thank you!

**Comment by ghost** [comment]
You're welcome. I was able to make a fix after some cursory research. Thanks for the handy plugin.
